### ISSUE TITLE
EPIC > Sanity Plugin Alpha

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt#162]
# Why
The CMS Daap is a web3 CMS in a box for non-technical users that handles the publishing and naming of content to Kubelt.

# How
The alpha version of the CMS will be delivered as a Sanity Studio plugin that adds a login and workflow step to publish content to Kubelt.

## Login
When the workflow is component is loaded (see below) a user should be prompted to login by providing entering a passphrase. Login is completed by requesting the users wallet to sign the collected passphrase and using the resulting signature as the seed for a new master key material using the Kubelt SDK.

> NOTE: Using Sanity Studio's [part system](https://www.sanity.io/docs/parts) may be required? Look at the MUX plugin for example.

The SDK will use the master key material to bootstrap the app by loading the users "Me DAG" into the local quad store.

## Workflow

This step [grabs a the document being published](https://www.sanity.io/docs/document-actions#362c883e4421) and passes the draft to the Kubelt SDK to generate a schema and translate the document to RDF/Quads. The SDK will then pack the contents and publish to IPFS and return the corresponding CIDs. The root of this collection will also be named by the CID and published to Kubelt.

This published information will be returned to the plugin and the workflow will then [patch](https://www.sanity.io/docs/http-patches) the document with this information.

> NOTE: Users are expected to run add their own schemas as they would currently do with Sanity.

> TBD: How does naming work with this workflow step if there are multiple named items/collection?

# What

* [x] kubelt/kubelt#6
* [x] kubelt/sanity-plugin-kubelt#24
* [x] kubelt/sanity-plugin-kubelt#23
* [x] kubelt/sanity-plugin-kubelt#12
* [x] kubelt/sanity-plugin-kubelt#13
* [x] kubelt/sanity-plugin-kubelt#25
* [x] kubelt/sanity-plugin-kubelt#27
* [ ] kubelt/sanity-plugin-kubelt#34
* [x] kubelt/sanity-plugin-kubelt#50
* [ ] kubelt/sanity-plugin-kubelt#51
* [ ] FEAT(CMS DAAP)> Prompt user to attribute other properties to content (e.g., protected/hidden via mutliauth, etc TBD). 
* [ ] FEAT(CMS DAAP)> Send the document with marked name field to the SDK
* [ ] FEAT(CMS DAAP)> Take SDK response and patch the document with the kubelt name CID (plus any other metadata)
* [ ] FEAT(CMS DAAP)> Complete the workflow

## Dependencies
kubelt/kubelt#3 

# Notes
- https://www.notion.so/kubelt/CMS-Dapp-719f45954580499b866e893e2f49d450
- http://ipfs.io/ipfs/QmNfXy5uCQjEWabnAsvJJPGkKNc6wSZu9M9w2cNxQ8WTo8
- https://www.sanity.io/docs/parts
- https://www.sanity.io/docs/document-actions#362c883e4421

**Comment by maurerbot** [comment]
Will respec in GH Discussions
