### ISSUE TITLE
EPIC > Auth

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt#169]
- [ ] https://github.com/kubelt/kubelt/issues/150
- [x] #223
- [ ] https://github.com/kubelt/pando-network/issues/74
- [ ] https://github.com/kubelt/pando-network/issues/75

**Comment by maurerbot** [comment]
now tracking in Docs > Roadmap
