### ISSUE TITLE
EPIC > SDK Alpha

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt#3]
# Why
The Kubelt SDK is an easy to use daap development library backed by Kubelt. 

# How
The SDK is a functional clojure script library that handles the following functionality.

> NOTE: Dependencies like web3.js and IPFS must be made available in context and configured via DI

## Identity
Cryptography relating to authenticating the user and materializing their "Me DAG".

> NOTE: do we use [wat sign in WASM](https://github.com/mitschabaude/watsign)?

## Naming
Cryptography relating to naming content on the kubelt hypercore network.

> NOTE: do we use the [libsodium in WASM](https://github.com/jedisct1/libsodium.js/)?

> NOTE: IM3000 like collaboration out of scope for alpha.

# What
- [ ] An interface for resolving an identity into a session a bootstrapping a Kubelt Core
- [ ] An interface for resolving names and appending names to the Kubelt Core
- [ ] An interface for writing content and linking to the Kubelt Core

## Features
* #12 
* #13 
* #14 
* #19
* #20 
* #21
* #15 
* #45 
* #46 
* #47 
* #48 
* #49 
* #50 

## Bugs

* #8 
* #9 
* #11 
* #51 

## Meta

* #61 
* #22
* #23 

# Notes
- http://ipfs.io/ipfs/QmNfXy5uCQjEWabnAsvJJPGkKNc6wSZu9M9w2cNxQ8WTo8
- https://www.notion.so/kubelt/SDK-f3655ff7674442ca80de75a35483d7f4

**Comment by maurerbot** [comment]
Now tracking in docs roadmap
