### ISSUE TITLE
feat(config): Core Configuration API 

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt#316]
# Why

This ticket tracks implementation of the configuration API and related data structures, for cores.

# How

Cores have general configuration settings and configuration settings related to security.

## Sample Config Schemas

These schemas are intended to describe one, large config object that is retrieved from and sent to the core, completely. In order to change a setting, for now, the config object is retrieved, mutated and POSTed (see below) back to the core.

The fields within these schemas will be permissioned by the capability model (https://github.com/kubelt/kubelt/discussions/315). For example, permission to update the `id` child object will not include permission to update the `cors` object in the security schema. An attempt to mutate the object without sufficient permissions for any part of the request will invalidate the entire request.

### General Config

```
{
	"id": {
		"pfp": "address or data URI",
		"alias": "Was 'name' -- a URL-compatible string used to identify the core instead of its address. Default is empty. Could also implement a random name generator (eg, 'sister-square-knowledge')"
	},
	"client": {
		"ttl": "how long data from this core can be cached. -1 means 'no upper or lower bound'. Similar to the volatile keyword. This is equivalent to how often the client should 'refresh' the data to make sure it is fresh.",
		"mediaType": "See https://en.wikipedia.org/wiki/Media_type -- is there a particular media type that, for example, the gateway should apply to data from this core."
	},
	"aliases": ["a lookup table of cores that this core 'knows about', along with optional (local only) convenience labels (names). Note that physical cores have no concept of nesting or cryptographic relationship, this is simply an indication of logical organization. These aliases include routing information for requests within and between applications (see following object for an example).", {
		"alias": "this_is_a_service_core_alias",
		"provider": "libp2p://provider_address/rpc"
	}],
	"metadata": {
		"tags": ["a", "SET", "of", "zero", "or", "more", "arbitrary", "strings", "to", "help", "with", "resource", "identification", "and", "permissioning"],
		"version": "stirng. The version of the core. The current date (YYYY-MM-DD) when the default config was first requested."
	}
}
```

### Security Config

```
{
	"auth": {
		"jwt": {
			"ttl": 3600
		},
		"nonce": {
			"ttl": 60
		}
	},
	"cors": [{
		"Access-Control-Allow-Origin": "Each object in the `cors` set is an allowed origin. The gateway must pick one appropriately. Default is the string 'null'. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin",
		"Access-Control-Allow-Credentials": "Bool. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials",
		"Access-Control-Expose-Headers": "See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-expose-headers",
		"Access-Control-Max-Age": "See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-max-age",
		"Access-Control-Allow-Methods": "See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-allow-methods",
		"Access-Control-Allow-Headers": "See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-headers"
	}],
	"signers": [{
		"userId": "ThreeID address for a user.",
		"key": "key for user (format up for grabs)",
		"roles": [{
			"roleId": "name of role"
		}]
	}],
	"roles": [{
		"roleId": "name of role",
		"policies": ["policyId_1", "policyId_2"]
	}],
	"policies": [{
		"policyId": "name of policy",
		"capabilities": [{
			"capabilityId": "name",
			"caveats": [{
				"type": "filterResponse",
				"value": ["0x0c54fccd2e384b4bb6f2e405bf5cbc15a017aafb"]
			}]
		}]
	}],
	"capabilities": ["a list of objects describing capabilities this core provides. See https://github.com/kubelt/kubelt/discussions/315"]
}
```

**For more on capabilities and caveats see https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2255.md** the implementation for this API is intended to be a stub until we sort out the capability permissioning model.

## Data Structures

The above data should be captured using [data types supported by the Structured Clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types), notably including `object`.

**Deferred**: Stored objects should be [automerge](https://github.com/automerge/automerge) objects. <- we need to figure out a "why" on CRDTs for this.

## API

GraphQL deserves an honourable mention here: we should definitely build as though we will be using it in the future. In the meantime, we're going to do a simple REST/hypermedia API.

[As discussed](https://github.com/kubelt/kubelt/discussions/295) we will avoid versioning the API (though I added a `version` to the core itself).

[JSON-RPC](https://en.wikipedia.org/wiki/JSON-RPC) endpoints will be provided to retrieve and mutate the config data structure described above:

* `kb_getConfig`: retrieves the entire config object, filtered by permissions.
* `kb_setConfig`: sets the entire config object, filtered by permissions. This is an overwriting `POST` method, not a `PATCH` method.

## Exclusions

- This is not configuration for workers, which are a separate concern from cores.
- This is not configuration for durable objects, which are a separate concern from cores.
- This is not configuration for applications, which will be saved via the content API to the relevant user core.

# What

- [x] kubelt/kubelt-oort#23
- [ ] kubelt/kubelt-oort#24
- [x] kubelt/kubelt-oort#38
- [x] kubelt/kubelt-oort#39
- [x] kubelt/kubelt-oort#21
- [x] kubelt/kubelt-oort#36
- [ ] feat(config): Core Profile w/ PFP Upload
- [ ] kubelt/kubelt#337
- [ ] feat(config): Core profile GET endpoint
- [ ] feat(dapp): Profile Form + View
- [ ] feat(dapp): Wizard

# Notes

https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=231%3A3426

### Discussed in https://github.com/kubelt/kubelt/discussions/295

**Comment by alfl** [comment]
If we implement #270 (Oauth) we'll need a `redirect` in the `security` section, perhaps under the `cors` CNAMEs.

**Comment by maurerbot** [comment]
> If we implement #270 (Oauth) we'll need a `redirect` in the `security` section, perhaps under the `cors` CNAMEs.

This is addition to CORS (domain restricted authentication).  A three-legged approach to authentication would also require a CNAME

**Comment by maurerbot** [comment]
one thing I want really early is the ability to just add (or select from my NFTs) a PFP for my core. Essentially, gravatar API would be super simple "core activiation". Adding a task for this specifically.

The NFT search can probably be a client side thing.

**Comment by maurerbot** [comment]
@alfl  is the idea for hypermerge to have an append only object in durable storage?

**Comment by maurerbot** [comment]
@drew-patel for the apps side of things the master design is here: https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=231%3A3426

Could also add a task for the wizard which would include PFP

**Comment by maurerbot** [comment]
@alfl what is the purpose of these two settings?

> cacheTtl: which configures how long data from the core are persisted in cache. -1 for "dealer's choice" -- no upper or lower bound. Similar to the volatile keyword.
expiryTtl: which configures how long the data live within the core. -1 is "no expiry".

**Comment by alfl** [comment]
They're for parity with the current (pndo) implementation and based on customer requests, particularly `expiryTtl` for wiping staging environments.

Based on Discord chat with @crimeminister thinking now that the concept of expiry might attach more properly to the core, but then that gets into the deletion conversation: is that simply an "unpin" is it a request to flush, etc.

**Comment by alfl** [comment]
> @alfl is the idea for hypermerge to have an append only object in durable storage?

Yes, but to @Cosmin-Parvulescu's point this is probably Automerge objects that we store in our own ledger? Giving it some more thought.

**Comment by alfl** [comment]
Updated ticket to capture feedback.

- tags, in future, could be a list of objects. Currently a list of strings for simplicity.
- `name` is a kind of `alias` for the core, so if there is a simplification in combining the concepts that's AOK.

**Comment by alfl** [comment]
```
{
  "account": {
    "publicKey": "0x040597d6d16111499ba10f95d77b9a26ab8c6a12f9a585eb4107129f78d6cab23bc738212852d7c5f79061244d76454c4b1f83ed4b5d8671318cb78b699fb736c4"
  },
  "address": "0xD1e73857c4dD788360cDE374c0C001492AC6CB2c",
  "claimed": true,
  "issuer": "0xD1e73857c4dD788360cDE374c0C001492AC6CB2c",
  "name": "",
  "auth": {
    "jwt": {
      "alg": "ES256",
      "signingKey": {
        "publicKey": {
          "kty": "EC",
          "x": "tHni9MxITc48OpZrNJUOVjPY6yB8l4s2KF9IEKREeUA",
          "y": "a6p9ywhKefU0zwQBoT_4FWLdmLZrLPhd_9MGRfCC-eM",
          "crv": "P-256"
        },
        "privateKey": {
          "kty": "EC",
          "x": "tHni9MxITc48OpZrNJUOVjPY6yB8l4s2KF9IEKREeUA",
          "y": "a6p9ywhKefU0zwQBoT_4FWLdmLZrLPhd_9MGRfCC-eM",
          "crv": "P-256",
          "d": "HGQSyKsogaXr2fsFRUVylk3AcYUE8X5-vx6mvXYxXxs"
        }
      },
      "ttl": 3600
    },
    "nonce": {
      "length": 24,
      "ttl": 60
    }
  }
}
```

**Comment by alfl** [comment]
cf: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2255.md

**Comment by billkube** [comment]
> > Updated ticket to capture feedback.
> > 
> > * tags, in future, could be a list of objects. Currently a list of strings for simplicity.
> > * `name` is a kind of `alias` for the core, so if there is a simplification in combining the concepts that's AOK.
> 
> @Cosmin-Parvulescu just mentioned this to me, right now i am making them as named kv entries but it could go in the config. putting it in the config puts an upper bound on how many aliases we support, since having many entries will bloat the config

another consideration is privacy and other users accessing your aliases. a core may elect to make its aliases public, or specific ones public. in this case it's better to be in the KV. 

if they are in config, you are retrieving the entire set of aliases.

**Comment by Cosmin-Parvulescu** [comment]
Still wondering about some configuration aspects, such as POST just overwriting the entire object. I think at this point, the entire config object will be POSTed every time from the client. As such, I think alias state will also be part of this post if I understood @alfl 's idea correctly.

**Comment by alfl** [comment]
This ticket is quite large and is likely entirely a Starship concern (ie, not really related to 3ID).

**Comment by alfl** [comment]
The rest is conflated with profile so closing.
