### ISSUE TITLE
feat(config): Core Profile and PFP Via NFT

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt#337]
# Why

Expanding the Core config with profile configuration and API provides Kubelt users with convenient Gravatar-like features that wallets and developers can access.

# How

### Profile Config

Profile config object in core should support (all optional):
- Display name
- Location
- Email
- About
- Socials (Twitter, Discord, Instagram, Telegram)
- List of websites

### Profile Avatar

A Core should fetch and return a users NFTs. A selected NFT should be assignable as the Core's Avatar.

See Figma link below for visual reference.

### Endpoints

Cores should expose RPC endpoints callable via injected providers and/or our SDK. We may need our own provider in the near term so we can add headers, otherwise we may move headers into the body.

# What

- [x] kubelt/kubelt-oort#31
- [x] feat(sdk): add JsonRpcProvider (and optional headers) to wallet 
- [x] https://github.com/kubelt/kubelt/issues/316
- [x] kubelt/kubelt-oort#45
- [x] kubelt/kubelt-oort#47
- [ ] kubelt/three-id#32

# Notes

- Related: https://github.com/kubelt/kubelt/discussions/349
- Related: https://github.com/kubelt/kubelt/discussions/295
- Design: https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=620%3A6617
- Customer headers for provider: https://github.com/ethers-io/ethers.js/issues/1201
- https://docs.ethers.io/v5/api/providers/jsonrpc-provider/

**Comment by szkl** [comment]
>  feat(core): when localhost return a localhost provider URL with a hostname header with would be host

@maurerbot trying to recall which part is supposed to set the header? The title sounds more like a client-side task. Could you write down an example workflow?

**Comment by maurerbot** [comment]
Yes, it's a client side task. The response body should be set in the SDK wallet and used to construct a provider

**Comment by Cosmin-Parvulescu** [comment]
Some notes and questions regarding profile:

# Notes
- 3Id is either a gateway to an app or wraps the gateway;
- 3Id is its own thing;
- Relay is important functionality not yet available;
- JWTs will include the capability model; 
- Profile core requests (~kb_getNfts - relay, ~kb_getProfile, ~kb_setProfile - with validation). 

# Questions
- What does it mean to be a gateway or to wrap the gateway? (@alfl)
- Do we want it in the same tech stack as the Dapp or something different (i.e. NextJS or whatever)? (@maurerbot @alfl @drew-patel)
- Is the Wallet Connect Popup reusable? Do we need all providers or just Metamask? (@maurerbot @drew-patel)
- Would the account(s) state management (i.e. list of accounts and associated JWTs) be handled in the SDK or the client app? (@crimeminister @drew-patel)
- Is the profile ultimately just a JSON blob in its own keystore? (@alfl @szkl)

**Comment by crimeminister** [comment]
@Cosmin-Parvulescu I think we may want to provide an easy path by making the SDK support credential management, but for those who'd rather do without for whatever reason, to support a roll-your-own approach for those who'd rather have things managed directly by their dapp.

**Comment by alfl** [comment]
Almost complete, pending some 3ID implementation work potentially related to SDK.
