### ISSUE TITLE
CHORE(examples): TODO app

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt#348]
# Why

A new examples folder with a TODO app would help new developers read and understand how to use the SDK.

# What

- [ ] chore(todo app): a base next.js todo app (react or vue) 
- [ ] chore(todo app): use SDK to auth into personal core
- [ ] chore(todo app): use SDK to create "todo app" core and auth in
- [ ] chore(todo app): use SDK to fetch todo app core aliases
- [ ] chore(todo app): use SDK to auth into todo app core
- [ ] chore(todo app): use SDK to store todo app state
- [ ] chore(todo app): use SDK to permission more users to todo app core

# Notes

- N/A
