### ISSUE TITLE
FEAT(CLJS): Extract profile settings screen

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [kubelt/kubelt#549]
BONUS: It would be nice to have a way to transform CLJS entity mappings into Typescript types / interfaces.

- [ ] #550

We need to add another step to the 3iD Expo funnel, the end of which might require the user to land on their `profile settings`  page (from now on The Screen). This page should be extracted from [CLJS App](https://github.com/kubelt/three-id) and implemented in the [3iD Expo App](https://github.com/kubelt/kubelt/tree/main/three-id).

- [x] #561
- [x] Use **useAccount** to respond to current profile (handled in #565)

When translating forms, or other system components which are available either as Expo, React Native or React Native Web (RNW) components, we want to use those instead of the ones we currently have. So most form elements will be translated into RNW equivalents. For example [TextInput](https://necolas.github.io/react-native-web/docs/text-input/).

- [x] #564

Expo's alternative to CLJS's state management might be [AsyncStorage](https://docs.expo.dev/versions/latest/sdk/async-storage/), so that could be used to maintain state. Currently, the Expo app maintains state by observable modules and hooks, but that is prone to change within this sprint.

- [x] Use AsyncStorage to replace ReFrame for the backing of the screen fields (handled in #565)

Expo doesn't really suggest tailwind or others, and most React Native frameworks suggest the usage of javascript styled components. As such, one major hurdle to overcome will be translating the CLJS generated CSS into styled components. This could be easier if using the browser for most elements.

- [x] Adapt CSS to Expo sheets, preserving CLJS layout (partially handled in #565)

Extra considerations:
- Mobile layout;
- Testing will be handled in another ticket (to be discussed);
- Controls that could be groked: React Native Web (already linked), [React Native](https://reactnative.dev/docs/next/components-and-apis) and [Expo](https://docs.expo.dev/versions/latest/).

**Comment by Cosmin-Parvulescu** [comment]
@alfl I believe this can be closed for now. There's more to add, like navigation and the details screen but I will handle these in other tickets as part of the tracker #551.

**Comment by Cosmin-Parvulescu** [comment]
Closing as creator
