### ISSUE TITLE
FEAT(DD): Implement DataDog Tracking

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#552]
# Why

We want to track users to get insight into how they're using 3iD in order to improve their experience.

# What

Recently/currently DataDog RUM tracking has been blocked by the client with a `403` error. This should be addressed if necessary.

Next [we should be using RUM to track user actions](https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/). These should be tagged according to our (light) [specification](https://www.notion.so/kubelt/DataDog-Analytics-Schema-0f92f08f72fd4b6a9bc528cd38d02765).

Last, we should be able to track a session consistently across flows. In this case that means from screen 1 through all of screen 2. This might require configuration -- please comment below if this is or is not the case.

# How

Please decompose into a set of likely tickets to discuss.

- [x] Investigate / fix 403 error:
- Update deployment strategy to include datadog env vars
- Deploy app with env variables set
- Handled in https://github.com/kubelt/kubelt/pull/538

- [x] kubelt/three-id#96
- Initialize RUM SDK for session recording
- Request session recording
- Validate in dashboard

- [ ] Use datadog API Client
- * So that app can send data to DataDog

- [ ] Implement specification events (possibly time consuming):
- Adjust RUM env to follow specification
- Create requested metrics as DataDog Metrics
- * This feels like we might need to override the default RUM init somehow or manually add events that follow our specifications; more documentation or actual implementation would be needed. 
- * Tags could be used for individual metrics to simulate other properties (i..e session).
- * Track individual Metrics on individual tickets, sometimes explodes in complexity (for example following entire signing flow).
- * We need to make sure metrics is correct data, could take some time and trial & error.

- [ ] Hook extension events (possibly time consuming):
- Metamask connections, disconnections, clicks if possible
- * RUM doesn't seem to handle these by default so might need to hook them manually if desired.

- [ ] Link unrelated properties in e2e session:
- Create an end to end funnel in datadog for Marketing Site + 3iD
- * From the documentation it feels that we might achieve this using DataDog UI (Metrics) only as we might be able to link user journey across multiple properties using the RUM Dashboard. Needs more investigation or actual implementation. Prerequisite on access to 2nd property data.
- * Probably doesn't work but if MM dispatches event we can hook into that.

- [ ] Create dashboards

# Notes

- https://www.notion.so/kubelt/DataDog-Analytics-Schema-0f92f08f72fd4b6a9bc528cd38d02765
- https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/

**Comment by alfl** [comment]
We're getting data logged to the dog! Closing this here and we'll make something finer-grained when we have more resolution on it. As a preview that will be: adding custom action names (likely ones that map to attributes used in automated tests), potentially creating custom event types that will be related to particular screens, etc.

The general task is complete.
