### ISSUE TITLE
BUG(3iD): Polish Tracker

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#553]
# Why

This is an omnibus ticket intended to track several disparate polish items reported in the production 3iD early access gate.

# What

- [x] Expo output in console: `expo-app-loading is deprecated in favor of expo-splash-screen: use SplashScreen.preventAutoHideAsync() and SplashScren.hideAsync() instead. https://docs.expo.dev/versions/latest/sdk/splash-screen/`. Please implement this suggestion. https://github.com/kubelt/kubelt/pull/532
- [x] Please update screen 2B message by **adding** "It could take a few seconds for the message to appear. If it does not appear try clicking on your wallet." https://github.com/kubelt/kubelt/pull/531
- [x] When the user gets to the gate (screen 2C) and clicks "Try Different Wallet" they are sent back to 2A. When they then select Metamask the flow does not re-start. They should be asked to re-connect / re-sign the message. https://github.com/kubelt/kubelt/pull/533
- [ ] Please implement new favicons (for now, see Discord: https://discord.com/channels/790660849471062046/956176245622730752/994605303167455232). This should fix the issue with the low-rez application icon in the wallet dapp connection popup (https://media.discordapp.net/attachments/956176245622730752/994604910576418836/unknown.png). https://github.com/kubelt/kubelt/pull/530
- [ ] Handle wallet connect / sign exceptions ([#](https://discord.com/channels/790660849471062046/956176245622730752/994984731550691338))

# Notes

- As a general point around engineering standards console output should be clean (ie, empty) for a production build.

**Comment by Cosmin-Parvulescu** [comment]
Parking this for now as favicons are not yet designer provided and metamask exceptions are at this point low-gain, high-effort implementations. Possibly impossible.

**Comment by alfl** [comment]
I'll close and we can re-open polish in `kubelt`.
