### ISSUE TITLE
FEAT(mint): Implement Mint PFP Screen Flow

### ISSUE THREAD

**Issue by alfl** [kubelt/kubelt#623]
# Why

We want to allow users to mint an NFT of a beautiful, unique, algorithmically generated image that represents their wallet address (i.e., that is deterministically generated by an algorithm seeded by the entropy of their address hash).

This is valuable to us because:

* This serves as a reward, or incentive, for using and discussing 3iD.
* It makes sure that users can easily create an NFT if they don't have any yet.
* It exercises the Starport platform and builds reusable capabilities.

# What

**New**: When we detect one or more 3iD invitation NFTs there are different screen flows required (cc @Cosmin-Parvulescu):

- If one NFT, we show it to the user along with a "continue to 3id" button.
- If more NFTs, we show them to the user in a dropdown along with a "continue to 3id" button.
- In both cases we display a message that they can now transfer the NFT on secondary markets.

* [See Notion for business requirements and acceptance tests.](https://www.notion.so/kubelt/Mint-PFP-e757f41ae16343e4abc5f3b8f8a44980)
* [See Figma for screen flows.](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=2143%3A9687)

There will be several touchpoints with Oort that require new methods (for example, to trigger the minting flows).

**Note** that this _will_ include image generation and so will need the [NFTar generator](https://github.com/kubelt/kubelt/pull/606) made available as a "service core".

**Screen Flow**

* Redirect to profile settings should only be on first gate pass. If logging in again you should see your home page / profile page.

# How

We need to add additional screens / panels on the funnel layout. These should support the Mint PFP flow and allow the user to either complete the journey and receive a minted NFT Profile Picture, or to skip it and go straight to Profile Settings screen.

- [x] kubelt/kubelt#624
- [x] kubelt/kubelt-oort#160
- [x] kubelt/kubelt#635

We should enhance the Oort Cloud with the ability to present pre-mint data so that we may add it to the funnel and inform the user.

- [ ] FEAT(mint): Generate Display-Only NFT Image
- [ ] FEAT(mint): Implement Pre-Mint Data Endpoint

Once we can get the asset data it's trivial to redirect to the screen and display it.

- [ ] FEAT(mint): Update Profile Data With Pre-Minted NFT URL
- [x] kubelt/kubelt#625

Similarly to generating the pre-mint data, once the user requests the NFT PFP, Oort should be able to generate a Mint Voucher so that we can implement "lazy minting" (ie, user pays gas). The Oort-signed Mint Voucher is sent to the client and included by the client (as-is) in a user-signed transaction to the PFP smart contract.

- [x] kubelt/kubelt-oort#159

Afterwards, client-side, request the mint voucher and generate the minting transaction with it.

- [x] FEAT(mint): Generate and Send Minting Transaction (Client-Side) (handled in #624)
- [x] FEAT(mint): Enable Retrying Failed Transactions (handled in #624)
- [ ] FEAT(Oort): Generate NFT Images in Several Sizes

Both on success, or skipping, the funnel should take the user eventually to the `/profile/settings` page

- [x] kubelt/kubelt#627
- [x] kubelt/kubelt#633

# Notes

- The PFP can be minted and is not transferable (i.e., is [soulbound](https://vitalik.ca/general/2022/01/26/soulbound.html)). This is a requirement for the contract.

**Comment by alfl** [comment]
cc @szkl -- for discussion on new Oort methods needed for minting.

**Comment by maurerbot** [comment]
The why needs to be expanded...

> We want to reward users for trying 3iD and to make sure they have an NFT to use as a PFP.

This reason is tied directly to the invite card NFT. The PFP minting is optional.

Some requirements that are in the user stories that need to be captured is (see notion stories):
- the invitation code is needed to get in but is transferable once they recieve their claim
- the pfp can be self minted but should not be transferable (soul bound like)
- redirect to profile settings should only be on first gate pass. if logging in again you should see your home page / profile page.

**Comment by maurerbot** [comment]
The pfp image should have multiple resolutions saved when generated. Dimensions are likely to be a square so one resolution should be large enough that it can be used as a cropped / zoomed cover image.

**Comment by alfl** [comment]
For clarity, there are two NFTs we're talking about here: one for membership/invitations and one for profile pictures. Will update.

**Comment by crimeminister** [comment]
@maurerbot Does it make sense to mint SVGs (or some vector format) to allow scaling, rather than generating one (or more) fixed-size raster images?

**Comment by Cosmin-Parvulescu** [comment]
> * redirect to profile settings should only be on first gate pass. if logging in again you should see your home page / profile page.

This is part of the effort in https://github.com/kubelt/kubelt/issues/551; until we have a profile / home page we can't really redirect to that so perhaps outside the scope of this particular ticket?

**Comment by maurerbot** [comment]
> @maurerbot Does it make sense to mint SVGs (or some vector format) to allow scaling, rather than generating one (or more) fixed-size raster images?

With the current algo we can't generate an SVG

**Comment by alfl** [comment]
> - The current Reality as understood by @Cosmin-Parvulescu means that we're going to pre-generate NFTs, so that means generating small and large sizes will be done in the same pass and potentially the large URL can be used in pre-mint screen.

For clarity, because this has been changed recently: no.

We're going to lazy-mint, not pre-mint, based on an image generator. The image generator relies on the target wallet address and so cannot be run before we know the address asking for the mint (via a voucher system).

We will likely kick off generation of a sufficiently sized image as soon as we know the authorized address (ie, once a `3id.enter` claim is retrieved). "Sufficient" because generating a 4k image takes a while and can be done after the user has decided to mint, whereas we can quickly generate a smaller (eg, 800px) image for display purposes within the Mint PFP screen flow.

**Comment by alfl** [comment]
Update to the flow: https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=2333%3A10160

If the user has multiple invitations they can select a particular invitation with which to continue.

**Comment by alfl** [comment]
Updates throughout the **How** section.

**Comment by Cosmin-Parvulescu** [comment]
> New: When we detect one or more 3iD invitation NFTs there are different screen flows required (cc @Cosmin-Parvulescu):

> If one NFT, we show it to the user along with a "continue to 3id" button.
> If more NFTs, we show them to the user in a dropdown along with a "continue to 3id" button.
> In both cases we display a message that they can now transfer the NFT on secondary markets.

These particular concerns, as well as

> Update to the flow: https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=2333%3A10160
> 
> If the user has multiple invitations they can select a particular invitation with which to continue.
> 
> cc: @Cosmin-Parvulescu requirements ("**New**") added to **What**, above.

are handled in #642

**Comment by alfl** [comment]
Launched!
